import type { Metadata } from "next";


import "./globals.css"
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <nav className="flex space-x-3">
          <Link href="/">Home</Link>
          <Link href="/users">Users</Link>
          <Link href="/about">About</Link>
          <Link href="/files">Files</Link>
          <Link href={{
            pathname: "/files/file1",
            query: {
              ho: "Sample Specific file",
              message: "I am fine"
            }
          }}>Specific File</Link>
          <Link href="/docs">Docs</Link>
          <Link href="/blogs">Blogs</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}